name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  firebase-deploy:
    runs-on: ubuntu-lasted
    
    steps:
      - uses: actions/checkout@master
      - uses: action/setup-node@master
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
