name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  firebase-deploy:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm build
      - uses: w9jds/firebase-action@master
        with:
          args: functions:config:set someservice.key=secrets.API_KEY someservice.auth=secrets.AUTH_DOMAIN someservice.database=secrets.DATABASE_URL someservice.project=secrets.PROJECT_ID someservice.storage=secrets.STORAGE_BUCKET someservice.messaging=secrets.MESSAGING_SENDER_ID someservice.app=secrets.APP_ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}     
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
